---
  title: 'Dungeons and Dragons: monsters'
author: "Sebestyén V.Nagy"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r, include=TRUE}
install.packages("tidyr")
install.packages("Rsampling")
library(Rsampling)
install.packages("recipes")
library(recipes)
install.packages("parsnip")
library(parsnip)
install.packages("tune")
library(tune)
install.packages("yardstick")
library(yardstick)
library(tidyr)
library(tidyverse)
library(dplyr)
library(psych)
install.packages("tidymodels")
library(tidymodels)
```

```{r, include=TRUE}
DandData <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/refs/heads/main/data/2025/2025-05-27/monsters.csv")
view(DandData)
describe(DandData)
```

```{r, include=TRUE}

DandData<- DandData %>% 
  mutate(size = factor(size),
         type = factor(type),
         category = factor(category),
         alignment =factor(alignment))

summary(DandData)
```


Making some plots to visualize trends
```{r, include=TRUE}
DandData %>% 
  select(ac, cr) %>% 
  ggplot() +
  aes(x = ac, y = cr) +
  geom_point() +
  geom_smooth()

DandData %>%
ggplot() +
aes(x = size, fill = type) +
geom_bar()

```

first simple supervised learning model

```{r, include=TRUE}
Ddsplit <- initial_split(DandData,
                         prop = 0.75,
                         strata = ac)

lm_model <- linear_reg() %>% 
  set_engine("lm") %>% 
  set_mode("regression")

Ddlastfit <- lm_model %>% 
  last_fit(cr ~ ac,
           split = Ddsplit)

Ddlastfit %>% 
  collect_metrics()
ddlastfit_model1 <- Ddlastfit %>% 
  collect_predictions()


ggplot(ddlastfit_model1, aes(x = cr, y = .pred)) +
  geom_point() +
  geom_smooth()

```
Well, its seems that the rsquare is 0.678 which is pretty high but I think it could be improved still, with some other variable. And the Rmse is pretty high 3.81 considering Cr goes up to 30 so the model is amiss with more than 10% on average. 

```{r, include=TRUE}

```